player_limit: -1
ip_forward: true
permissions:
  default:
    - bungeecord.command.server
    - bungeecord.command.list
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
timeout: 30000
log_pings: true
log_commands: false
online_mode: false
servers:
  lobby:
    motd: '&1Just another BungeeCord123 - Forced Host'
    address: 192.168.212.121:25565
    restricted: true
  creative:
    motd: Welcome to the Creative world
    address: 192.168.19.158:25565
    restricted: true
listeners:
  - query_port: 25577
    motd: '&1Another Bungee server123'
    priorities:
      - creative
    bind_local_address: true
    tab_list: GLOBAL_PING
    query_enabled: false
    host: 0.0.0.0:25577
    forced_hosts:
      pvp.md-5.net: pvp
    max_players: 5
    tab_size: 100
    ping_passthrough: false
    force_default_server: true
    proxy_protocol: false
disabled_commands:
  - disabledcommandhere
network_compression_threshold: 256
groups:
  md_5:
    - admin
connection_throttle: 4000
connection_throttle_limit: 3
stats: f2876aa6-74d2-468c-90ee-1377111f1c9f
forge_support: false
inject_commands: false
